//! Build script: parse `crates/rustricted-std/src/lib.rs` and emit a static
//! table of `(simple_fn_name, [param_names...])` tuples for every `pub fn`
//! found at any module depth. The lowering pass uses this table to seed the
//! `CalleeRegistry` so that cross-crate named-arg call sites like
//! `rustricted_std::fs::write_text(path: p, contents: c)` can be lowered to
//! positional form against the *real* signature.
//!
//! Design choice (RT-32): bundled signature index at build time, generated
//! from the canonical `rustricted-std` source. Compared to the other two
//! options considered:
//!
//! - "parse-on-demand via cargo metadata" — works for *any* crate but slow
//!   and brittle (would need a cargo metadata invocation at lower time).
//! - "compile-time macro registry" — most idiomatic, but requires runtime
//!   registration and a shared static; harder to thread through a token-
//!   level rewrite that runs out-of-process.
//!
//! The bundled-index approach is fast (a single `include!`), deterministic
//! (rebuilds when `rustricted-std/src/lib.rs` changes), and self-contained.
//! Limitation: it only covers `rustricted-std`. Other strict crates that
//! want cross-crate named args will need a follow-up (RT-33 candidate)
//! that generalises this to any dependency.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Locate `rustricted-std/src/lib.rs` relative to this crate's manifest.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let std_lib = PathBuf::from(&manifest_dir)
        .join("..")
        .join("rustricted-std")
        .join("src")
        .join("lib.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", std_lib.display());

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = PathBuf::from(&out_dir).join("std_signatures.rs");

    // If the source isn't readable for any reason, emit an empty table so
    // the crate still compiles. (Tests and lint passes don't care about the
    // table's contents, only that the symbol exists.)
    let source = match fs::read_to_string(&std_lib) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "rustricted-lower build.rs: could not read {} ({e}); emitting empty index",
                std_lib.display()
            );
            fs::write(
                &out_path,
                "pub static STD_SIGNATURES: &[(&str, &[&str])] = &[];\n",
            )
            .expect("write empty std_signatures.rs");
            return;
        }
    };

    let file: syn::File = match syn::parse_file(&source) {
        Ok(f) => f,
        Err(e) => {
            eprintln!(
                "rustricted-lower build.rs: syn parse error on {} ({e}); emitting empty index",
                std_lib.display()
            );
            fs::write(
                &out_path,
                "pub static STD_SIGNATURES: &[(&str, &[&str])] = &[];\n",
            )
            .expect("write empty std_signatures.rs");
            return;
        }
    };

    // name -> param-list, with ambiguity tracking (drop names whose
    // signatures disagree across modules so we don't mis-lower).
    let mut sigs: HashMap<String, Vec<String>> = HashMap::new();
    let mut ambiguous: std::collections::HashSet<String> = std::collections::HashSet::new();
    walk_items(&file.items, &mut sigs, &mut ambiguous);

    let mut out = String::new();
    out.push_str("// @generated by rustricted-lower/build.rs — do not edit.\n");
    out.push_str("pub static STD_SIGNATURES: &[(&str, &[&str])] = &[\n");
    let mut keys: Vec<&String> = sigs.keys().collect();
    keys.sort();
    for name in keys {
        let params = &sigs[name];
        out.push_str("    (\"");
        out.push_str(name);
        out.push_str("\", &[");
        for (i, p) in params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('"');
            out.push_str(p);
            out.push('"');
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write std_signatures.rs");
}

fn walk_items(
    items: &[syn::Item],
    sigs: &mut HashMap<String, Vec<String>>,
    ambiguous: &mut std::collections::HashSet<String>,
) {
    for item in items {
        match item {
            syn::Item::Fn(f) => record_fn(&f.sig, &f.vis, sigs, ambiguous),
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    walk_items(inner, sigs, ambiguous);
                }
            }
            _ => {}
        }
    }
}

fn record_fn(
    sig: &syn::Signature,
    vis: &syn::Visibility,
    sigs: &mut HashMap<String, Vec<String>>,
    ambiguous: &mut std::collections::HashSet<String>,
) {
    // Only index pub fns — those are the ones a downstream caller could
    // name. Private helpers aren't reachable cross-crate.
    if !matches!(vis, syn::Visibility::Public(_)) {
        return;
    }
    let name = sig.ident.to_string();
    if ambiguous.contains(&name) {
        return;
    }
    let mut params: Vec<String> = Vec::new();
    for input in &sig.inputs {
        match input {
            syn::FnArg::Receiver(_) => {} // skip self
            syn::FnArg::Typed(pat_type) => {
                if let Some(ident) = pat_ident(&pat_type.pat) {
                    params.push(ident);
                } else {
                    // Non-ident patterns (destructuring) — can't bind by
                    // name. Drop the whole entry to avoid lying about the
                    // signature.
                    sigs.remove(&name);
                    ambiguous.insert(name);
                    return;
                }
            }
        }
    }
    match sigs.get(&name) {
        Some(existing) if existing != &params => {
            sigs.remove(&name);
            ambiguous.insert(name);
        }
        Some(_) => {}
        None => {
            sigs.insert(name, params);
        }
    }
}

fn pat_ident(pat: &syn::Pat) -> Option<String> {
    match pat {
        syn::Pat::Ident(pi) => Some(pi.ident.to_string()),
        _ => None,
    }
}
