//! Build script: read the checked-in `crates/rustricted-std/std-signatures.txt`
//! manifest and emit a static `STD_SIGNATURES` table that the named-args
//! lowering pass uses to seed the `CalleeRegistry` for cross-crate calls
//! like `rustricted_std::fs::write_text(path: p, contents: c)`.
//!
//! Design history (RT-32 → RT-44):
//!
//! - RT-32 parsed `rustricted-std/src/lib.rs` directly with `syn` at build
//!   time. That worked as long as the std-shim source stayed plain Rust.
//! - RT-31 dogfooding discovered the circular trap: if `rustricted-std`
//!   itself is `#![strict]`-marked (a perfectly natural future state),
//!   `syn` rejects the named-arg / strict-marker syntax and the build
//!   script *silently* emits an empty `STD_SIGNATURES`, breaking
//!   cross-crate named-arg lowering everywhere downstream.
//! - RT-44 (this file) switches to a checked-in TOML-ish manifest. The
//!   manifest is auditable, the build is decoupled from `rustricted-std`'s
//!   source dialect, and freshness is enforced by
//!   `cargo xtask gen-std-signatures --check` in CI.
//!
//! Any parse error here is now a HARD FAILURE (panic) — empty
//! `STD_SIGNATURES` was the single nastiest silent footgun in the previous
//! design and we refuse to reintroduce it.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let sig_file = PathBuf::from(&manifest_dir)
        .join("..")
        .join("rustricted-std")
        .join("std-signatures.txt");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", sig_file.display());

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = PathBuf::from(&out_dir).join("std_signatures.rs");

    let source = fs::read_to_string(&sig_file).unwrap_or_else(|e| {
        panic!(
            "rustricted-lower build.rs: could not read {} ({e}). \
             This file is the checked-in source of truth for STD_SIGNATURES. \
             Run `cargo xtask gen-std-signatures` to regenerate it from \
             rustricted-std/src/lib.rs.",
            sig_file.display()
        )
    });

    let sigs = parse_manifest(&source).unwrap_or_else(|e| {
        panic!(
            "rustricted-lower build.rs: malformed manifest at {} ({e}). \
             Run `cargo xtask gen-std-signatures` to regenerate it.",
            sig_file.display()
        )
    });

    if sigs.is_empty() {
        panic!(
            "rustricted-lower build.rs: manifest at {} parsed to zero entries. \
             That would silently break cross-crate named-arg lowering. \
             Run `cargo xtask gen-std-signatures` to regenerate it.",
            sig_file.display()
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by rustricted-lower/build.rs from\n");
    out.push_str("// crates/rustricted-std/std-signatures.txt — do not edit.\n");
    out.push_str("pub static STD_SIGNATURES: &[(&str, &[&str])] = &[\n");
    let mut keys: Vec<&String> = sigs.keys().collect();
    keys.sort();
    for name in keys {
        let params = &sigs[name];
        out.push_str("    (\"");
        out.push_str(name);
        out.push_str("\", &[");
        for (i, p) in params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('"');
            out.push_str(p);
            out.push('"');
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write std_signatures.rs");
}

/// Parse the `std-signatures.txt` manifest into a `name -> [params]` map.
///
/// Lines starting with `#` and blank lines are ignored. Each data line is
/// `name:p1,p2,...`. Duplicates with mismatched param lists are a hard
/// error — the upstream generator is responsible for dropping ambiguous
/// names, so a duplicate here means the manifest has been hand-edited
/// incorrectly.
fn parse_manifest(source: &str) -> Result<HashMap<String, Vec<String>>, String> {
    let mut out: HashMap<String, Vec<String>> = HashMap::new();
    for (lineno, raw) in source.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (name, tail) = line
            .split_once(':')
            .ok_or_else(|| format!("line {}: missing `:` separator: {raw:?}", lineno + 1))?;
        let name = name.trim().to_string();
        if name.is_empty() {
            return Err(format!("line {}: empty function name", lineno + 1));
        }
        let params: Vec<String> = if tail.trim().is_empty() {
            Vec::new()
        } else {
            tail.split(',').map(|p| p.trim().to_string()).collect()
        };
        for p in &params {
            if p.is_empty() {
                return Err(format!(
                    "line {}: empty parameter name in `{name}`",
                    lineno + 1
                ));
            }
        }
        match out.get(&name) {
            Some(existing) if existing != &params => {
                return Err(format!(
                    "line {}: duplicate signature for `{name}` with mismatched params",
                    lineno + 1
                ));
            }
            _ => {
                out.insert(name, params);
            }
        }
    }
    Ok(out)
}
