//! Developer tooling. Subcommands:
//!
//! - `cargo xtask gen-docs [--check]` — regenerate auto-marked sections of
//!   `docs/SPEC.md` (or, with `--check`, fail if they would change).
//! - `cargo xtask check-emissions` — verify every implemented `Rule` variant
//!   has at least one emission site in the workspace.
//! - `cargo xtask gen-std-signatures [--check]` — regenerate
//!   `crates/trust-lower/std-signatures.txt` from
//!   `crates/trust-std/src/lib.rs` (lowered, then parsed with `syn`).
//!   With `--check`, fail if the checked-in manifest is stale. See RT-44.

// Stage-0 bootstrap crate (RT-76): plain Rust, built by stock `cargo`.
// xtask is dev tooling that runs *before* / *around* the toolchain build,
// so it stays free of the `#![strict]` syntax extensions.

mod std_signatures;

use anyhow::{bail, Context, Result};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const LINTS_BEGIN: &str = "<!-- BEGIN auto-generated: lints-table -->";
const LINTS_END: &str = "<!-- END auto-generated: lints-table -->";
const LOWER_BEGIN: &str = "<!-- BEGIN auto-generated: lowering-diagnostics-table -->";
const LOWER_END: &str = "<!-- END auto-generated: lowering-diagnostics-table -->";

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    let cmd = args.next().context("usage: cargo xtask <cmd> [--check]")?;
    let rest: Vec<String> = args.collect();
    let check_only = rest.iter().any(|a| a == "--check");

    match cmd.as_str() {
        "gen-docs" => gen_docs(check_only),
        "check-emissions" => check_emissions(),
        "gen-std-signatures" => gen_std_signatures(check_only),
        other => bail!("unknown subcommand: {other}"),
    }
}

/// Regenerate `crates/trust-lower/std-signatures.txt` from
/// `crates/trust-std/src/lib.rs`.
///
/// `trust-std` may itself be `#![strict]`-marked, so the source is
/// first passed through `trust_lower::lower()` to desugar any
/// Trust-specific syntax (strict markers, named args, pipes), then
/// parsed with `syn` to extract `pub fn` signatures. The manifest is the
/// build-time source of truth for `STD_SIGNATURES`; `build.rs` reads it
/// directly and never re-parses Rust source.
fn gen_std_signatures(check_only: bool) -> Result<()> {
    let root = repo_root()?;
    let lib_path = root.join("crates/trust-std/src/lib.rs");
    let manifest_path = root.join("crates/trust-lower/std-signatures.txt");

    let raw =
        fs::read_to_string(&lib_path).with_context(|| format!("reading {}", lib_path.display()))?;

    // Lower first: strips strict markers and rewrites any named-arg call
    // sites to positional form so `syn` can parse the result.
    let lowered =
        trust_lower::lower(&raw).with_context(|| format!("lowering {}", lib_path.display()))?;

    let file: syn::File = syn::parse_file(&lowered.source)
        .with_context(|| format!("syn parse of lowered {}", lib_path.display()))?;

    let mut sigs: std_signatures::SigMap = std::collections::BTreeMap::new();
    let mut ambiguous: std_signatures::NameSet = std::collections::BTreeSet::new();
    std_signatures::walk_items(&file.items, &mut sigs, &mut ambiguous);

    let out = std_signatures::render_manifest(&sigs, MANIFEST_HEADER);
    let entry_count = sigs.len();

    if check_only {
        let existing = fs::read_to_string(&manifest_path)
            .with_context(|| format!("reading {}", manifest_path.display()))?;
        if existing != out {
            eprintln!(
                "{} is stale — run `cargo xtask gen-std-signatures` to regenerate",
                manifest_path.display()
            );
            std::process::exit(1);
        }
        println!("{} is up to date", manifest_path.display());
        return Ok(());
    }

    fs::write(&manifest_path, &out)
        .with_context(|| format!("writing {}", manifest_path.display()))?;
    println!(
        "regenerated {} ({} entries)",
        manifest_path.display(),
        entry_count
    );
    Ok(())
}

const MANIFEST_HEADER: &str = "# @generated by `cargo xtask gen-std-signatures` from
# `crates/trust-std/src/lib.rs`. Do not edit by hand — run the xtask
# subcommand after modifying the std-shim source. CI verifies this file is
# fresh via `cargo xtask gen-std-signatures --check`.
#
# Format: one line per public `fn` in `trust-std`. Each line is
#
#     simple_fn_name:param1,param2,...
#
# `simple_fn_name` is the unqualified function name; the parameter list is
# its declared positional order. Functions whose simple names collide
# across modules with mismatched signatures are dropped at generation time
# (the lowering pass disambiguates by simple name only). Zero-arity fns
# appear with an empty tail: `channel:`.
#
# This file is the source of truth that `trust-lower/build.rs` reads
# to seed `STD_SIGNATURES`. The previous design parsed `lib.rs` with
# `syn` at build time, but that meant `trust-std` could never itself
# be `#![strict]`-marked (syn rejects named-arg syntax). The checked-in
# manifest removes that coupling — `lib.rs` can use any Trust feature
# the xtask knows how to lower. See RT-44.
";

/// Verify that every implemented `Rule` variant across all catalogues has at
/// least one emission site somewhere in `crates/`. Catches "I added a Rule
/// variant and forgot to wire it up."
///
/// An emission is recognised by either form:
/// - typed: `Rule::VariantName.code()` (preferred, type-safe)
/// - literal: `"RXXXX"` (the raw code as a string literal)
///
/// The variant's own catalogue file is excluded from the search so the
/// catalogue entry doesn't count as its own emission.
fn check_emissions() -> Result<()> {
    let root = repo_root()?;
    let crates_dir = root.join("crates");
    let files = collect_rust_files(&crates_dir)?;
    let texts: Vec<(PathBuf, String)> = files
        .into_iter()
        .map(|p| {
            let t = fs::read_to_string(&p).with_context(|| format!("reading {}", p.display()))?;
            Ok::<_, anyhow::Error>((p, t))
        })
        .collect::<Result<_>>()?;

    let mut failures: Vec<String> = Vec::new();
    let mut checked: usize = 0;

    for r in trust_lints::all_rules() {
        if !r.is_implemented() {
            continue;
        }
        check_one(
            r.code(),
            &format!("{r:?}"),
            "trust-lints/src/rules.rs",
            &texts,
            &mut failures,
        );
        checked += 1;
    }
    for r in trust_lower::rule::ALL {
        check_one(
            r.code(),
            &format!("{r:?}"),
            "trust-lower/src/rule.rs",
            &texts,
            &mut failures,
        );
        checked += 1;
    }
    if !failures.is_empty() {
        for f in &failures {
            eprintln!("error: {f}");
        }
        bail!("{} rule(s) have no emission site", failures.len());
    }

    println!("emissions: all {checked} implemented rules have at least one emission site");
    Ok(())
}

fn check_one(
    code: &str,
    variant: &str,
    catalogue_suffix: &str,
    texts: &[(PathBuf, String)],
    failures: &mut Vec<String>,
) {
    let typed = format!("Rule::{variant}.code()");
    let literal = format!("\"{code}\"");
    for (path, text) in texts {
        if path
            .to_string_lossy()
            .replace('\\', "/")
            .ends_with(catalogue_suffix)
        {
            continue;
        }
        if text.contains(&typed) || text.contains(&literal) {
            return;
        }
    }
    failures.push(format!(
        "{code} ({variant}): no emission site found — add `Diagnostic::error(Rule::{variant}.code(), …)` somewhere, or remove the variant"
    ));
}

fn collect_rust_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    walk_rs(dir, &mut out)?;
    Ok(out)
}

fn walk_rs(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let entry = entry?;
        let p = entry.path();
        if p.is_dir() {
            walk_rs(&p, out)?;
        } else if p.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(p);
        }
    }
    Ok(())
}

fn repo_root() -> Result<PathBuf> {
    // CARGO_MANIFEST_DIR is crates/xtask; parent twice is the workspace root.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .and_then(|p| p.parent())
        .context("could not derive workspace root from CARGO_MANIFEST_DIR")?
        .to_path_buf();
    Ok(root)
}

fn gen_docs(check_only: bool) -> Result<()> {
    let root = repo_root()?;

    // 1. docs/SPEC.md — replace the auto-marked catalogue tables in place.
    let spec_path = root.join("docs/SPEC.md");
    let spec_original = fs::read_to_string(&spec_path)
        .with_context(|| format!("reading {}", spec_path.display()))?;
    let lints_table = build_lints_table();
    let lowering_table = build_lowering_diags_table();
    let spec_updated = replace_section(&spec_original, LINTS_BEGIN, LINTS_END, &lints_table)?;
    let spec_updated = replace_section(&spec_updated, LOWER_BEGIN, LOWER_END, &lowering_table)?;

    // 2. docs/WRITING-TRUST.md — the fully-generated agent guide (RT-78).
    let guide_path = root.join("docs/WRITING-TRUST.md");
    let guide_existing = fs::read_to_string(&guide_path).unwrap_or_default();
    let guide_new = build_writing_trust();

    if check_only {
        let mut stale: Vec<String> = Vec::new();
        if spec_updated != spec_original {
            stale.push(spec_path.display().to_string());
        }
        if guide_new != guide_existing {
            stale.push(guide_path.display().to_string());
        }
        if !stale.is_empty() {
            for s in &stale {
                eprintln!("{s} is stale — run `cargo xtask gen-docs` to regenerate");
            }
            std::process::exit(1);
        }
        println!("docs are up to date (SPEC.md, WRITING-TRUST.md)");
        return Ok(());
    }

    if spec_updated != spec_original {
        fs::write(&spec_path, &spec_updated)
            .with_context(|| format!("writing {}", spec_path.display()))?;
        println!("regenerated {}", spec_path.display());
    }
    if guide_new != guide_existing {
        fs::write(&guide_path, &guide_new)
            .with_context(|| format!("writing {}", guide_path.display()))?;
        println!("regenerated {}", guide_path.display());
    }
    Ok(())
}

/// Header + intro for the generated agent guide. The rules below it are
/// derived from the live `trust-lints` registry, so the guide never drifts.
const WRITING_TRUST_HEADER: &str = "# Writing Trust — an agent's guide

<!-- @generated by `cargo xtask gen-docs` from the trust-lints rule registry.
     Do NOT edit by hand — change `crates/trust-lints/src/rules.rs` and
     regenerate. CI enforces freshness via `cargo xtask gen-docs --check`. -->

Trust is a strict dialect of Rust for LLM-authored code. Write code that obeys
the rules below and `trust check` passes; break one and it's a compile-time
error carrying the same `instead:` fix you see here. Load this file into your
context before writing Trust and you'll comply on the first try instead of
iterating against the checker.

**Two grammar extensions** (lowered to plain Rust before `rustc`):
- **Named arguments** past arity 1: call `f(width: 1920, height: 1080)`, not
  `f(1920, 1080)`. `trust fix` inserts the names for you.
- **A pipe operator** for chaining free functions onto a receiver — see
  `docs/SPEC.md` for the grammar.

**Activation:** `[package.metadata.trust] strict = true` in `Cargo.toml` for
whole crates built with `cargo trustc build`; `#![strict]` at the top of a file
for single-file `trust check` or per-file opt-in. See `docs/SPEC.md` for the
full grammar and per-rule detail.";

/// Build `docs/WRITING-TRUST.md` from the rule registry (RT-78).
fn build_writing_trust() -> String {
    let mut out = String::new();
    out.push_str(WRITING_TRUST_HEADER);
    out.push_str("\n\n## Rules\n\n");
    for rule in trust_lints::all_rules() {
        out.push_str(&format!("### {} · {}\n\n", rule.code(), rule.name()));
        out.push_str(&format!("- **Why:** {}\n", rule.rationale()));
        out.push_str(&format!("- **Instead:** {}\n\n", rule.instead()));
    }
    out
}

/// Build the non-strict lowering diagnostics table from the `Rule` enum in
/// `trust-lower`. Output is sorted by code.
fn build_lowering_diags_table() -> String {
    let mut rows: Vec<(&'static str, &'static str, &'static str, &'static str)> = Vec::new();
    for r in trust_lower::rule::ALL {
        rows.push((r.code(), r.pass(), "trust-lower", r.message_shape()));
    }
    rows.sort_by_key(|row| row.0);

    let mut out = String::new();
    out.push_str("| Code  | Pass                | Crate                  | Message shape                                       |\n");
    out.push_str("| ----- | ------------------- | ---------------------- | --------------------------------------------------- |\n");
    for (code, pass, crate_name, msg) in rows {
        let crate_quoted = format!("`{crate_name}`");
        out.push_str(&format!(
            "| {code:<5} | {pass:<19} | {crate_quoted:<22} | {msg:<51} |\n",
        ));
    }
    out
}

/// Build the lints catalogue markdown table from `trust_lints::all_rules()`.
///
/// Column widths are fixed to keep diffs minimal across runs.
fn build_lints_table() -> String {
    let rules = trust_lints::all_rules();
    let mut out = String::new();
    out.push_str("| Code  | Name                  | Phase | Severity |\n");
    out.push_str("| ----- | --------------------- | ----- | -------- |\n");
    for rule in rules {
        out.push_str(&format!(
            "| {:<5} | {:<21} | 1     | error    |\n",
            rule.code(),
            rule.name(),
        ));
    }
    out
}

/// Replace the text between `begin` and `end` marker lines with `content`.
/// Both markers are preserved; the content is sandwiched between them with
/// a leading and trailing blank line so the result is still valid markdown.
fn replace_section(input: &str, begin: &str, end: &str, content: &str) -> Result<String> {
    let begin_idx = input
        .find(begin)
        .with_context(|| format!("missing marker: {begin}"))?;
    let end_idx = input
        .find(end)
        .with_context(|| format!("missing marker: {end}"))?;
    if end_idx < begin_idx {
        bail!("end marker `{end}` appears before begin marker `{begin}`");
    }
    let before = &input[..begin_idx + begin.len()];
    let after = &input[end_idx..];
    Ok(format!("{before}\n\n{content}\n{after}"))
}
